best_buds/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from core.views import index, about, trim
from userprofile.views import signup


urlpatterns = [
    path('', index, name='index'),
    path('concentrates/', include('concentrates.urls')),
    path('strains/', include('strains.urls')),
    path('trim/', trim, name='trim'),
    path('about/', about, name='about'),
    path('sign-up/', signup, name='signup'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

concentrates/urls.py
from django.urls import path
from concentrates import views

app_name = "concentrates"

urlpatterns = [
    path("", views.concentrate_list, name="concentrate_list"),
    path("<int:pk>", views.concentrate_detail, name="concentrate_detail"),
    ]

strains/urls.py
from django.urls import path
from strains import views

app_name = "strains"

urlpatterns = [
    path("", views.strain_list, name="strain_list"),
    path("<int:pk>", views.strain_detail, name="strain_detail"),
    path('<int:pk>/delete/', views.strain_delete, name='strain_delete'),
    path('<int:pk>/edit/', views.strain_edit, name='strain_edit'),
    path('add-strain/', views.add_strain, name='add_strain'),
]

concentrates/models.py
from django.db import models

class Concentrate(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to='concentrates/img')

    def __str__(self):
        return self.name

core/models.py
from django.db import models

strains/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from multiselectfield import MultiSelectField

class Strain(models.Model):

    STOCK_CHOICES = (
        ("in_stock", "In stock"),
        ("limited_stock", "Limited stock"),
        ("out_of_stock", "Out of stock"),
        ("gone_forever", "Gone forever"),
        ("coming_soon", "Coming soon"),

    )

    TYPE_CHOICES = (
        ("indica", "Indica"),
        ("sativa", "Sativa"),
        ("hybrid", "Hybrid"),
        ("indica_hybrid", "Indica Hybrid"),
        ("sativa_hybrid", "Sativa Hybrid"),
    )

    EFFECT_CHOICES = (
        ("aroused", "Aroused"),
        ("creative", "Creative"),
        ("energetic", "Energetic"),
        ("euphoric", "Euphoric"),
        ("focused", "Focused"),
        ("giggly", "Giggly"),
        ("happy", "Happy"),
        ("hungry", "Hungry"),
        ("relaxed", "Relaxed"),
        ("sleepy", "Sleepy"),
        ("talkative", "Talkative"),
        ("tingly", "Tingly"),
        ("uplifted", "Uplifted"),
    )

    AROMA_CHOICES = (
        ('ammonia', 'Ammonia'),
        ('apple', 'Apple'),
        ('apricot', 'Apricot'),
        ('berry', 'Berry'),
        ('blueberry', 'Blueberry'),
        ('blue_cheese', 'Blue Cheese'),
        ('butter', 'Butter'),
        ('cheese', 'Cheese'),
        ('chemical', 'Chemical'),
        ('chestnut', 'Chestnut'),
        ('citrus', 'Citrus'),
        ('coffee', 'Coffee'),
        ('cream', 'Cream'),
        ('diesel', 'Diesel'),
        ('earthy', 'Earthy'),
        ('flowery', 'Flowery'),
        ('gassy', 'Gassy'),
        ('grape', 'Grape'),
        ('grapefruit', 'Grapefruit'),
        ('honey', 'Honey'),
        ('lavender', 'Lavender'),
        ('lemon', 'Lemon'),
        ('lime', 'Lime'),
        ('mango', 'Mango'),
        ('menthol', 'Menthol'),
        ('mint', 'Mint'),
        ('nutty', 'Nutty'),
        ('orange', 'Orange'),
        ('peach', 'Peach'),
        ('pear', 'Pear'),
        ('pepper', 'Pepper'),
        ('pine', 'Pine'),
        ('pineapple', 'Pineapple'),
        ('plum', 'Plum'),
        ('pungent', 'Pungent'),
        ('rose', 'Rose'),
        ('sage', 'Sage'),
        ('skunk', 'Skunk'),
        ('spicy_herbal', 'Spicy/Herbal'),
        ('strawberry', 'Strawberry'),
        ('sweet', 'Sweet'),
        ('tar', 'Tar'),
        ('tea', 'Tea'),
        ('tobacco', 'Tobacco'),
        ('tree_fruit', 'Tree fruit'),
        ('tropical', 'Tropical'),
        ('vanilla', 'Vanilla'),
        ('violet', 'Violet'),
        ('woody', 'Woody'),
    )

    name = models.CharField(max_length=50)
    stock = models.CharField(max_length=20, choices=STOCK_CHOICES, default="gone_forever")
    type = models.CharField(max_length=20, choices=TYPE_CHOICES, default="hybrid")
    effect = MultiSelectField(choices=EFFECT_CHOICES, max_choices=3, max_length=50)
    thc = models.IntegerField()
    breeder = models.CharField(max_length=30, null=True)
    lineage = models.CharField(max_length=75, null=True)
    aroma = MultiSelectField(choices=AROMA_CHOICES, max_choices=3, max_length=50)
    description = models.TextField()
    grow_info = models.TextField()
    image = models.ImageField(upload_to='strains/img')


    def __str__(self):
        return self.name

userprofile/models.py
from django.contrib.auth.models import User
from django.db import models

class Userprofile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)

strains/forms.py
from django import forms

from .models import Strain


class AddStrainForm(forms.ModelForm):
    class Meta:
        model = Strain
        fields = ('name', 'type', 'effect', 'thc', 'aroma', 'description', 'grow_info', 'image')

concentrates/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Concentrate


def concentrate_list(request):
    concentrates = Concentrate.objects.all().order_by('name')

    return render(request, "concentrates/concentrate_list.html", {
        'concentrates': concentrates,
    })


def concentrate_detail(request, pk):
    concentrate = get_object_or_404(Concentrate, pk=pk)

    return render(request, "concentrates/concentrate_detail.html", {
        'concentrate': concentrate
    })

core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')

def trim(request):
    return render(request, 'core/trim.html')

def about(request):
    return render(request, 'core/about.html')

strains/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect, get_object_or_404

from .forms import AddStrainForm
from .models import Strain



def strain_list(request):
    strains = Strain.objects.all().order_by('name')

    return render(request, "strains/strain_list.html", {
        'strains': strains,
    })


def strain_detail(request, pk):
    strain = get_object_or_404(Strain, pk=pk)

    return render(request, 'strains/strain_detail.html', {
        'strain': strain
    })


@login_required
def add_strain(request):
    if request.method == 'POST':
        form = AddStrainForm(request.POST)

        if form.is_valid():
            strain = form.save(commit=False)
            strain.save()

            messages.success(request, 'Strain created successfully.')

            return redirect('strain_list')
    else:
        form = AddStrainForm()

    return render(request, 'strains/add_strain.html', {
        'form': form
    })


@login_required
def strain_delete(request, pk):
    strain = get_object_or_404(Strain, pk=pk)
    strain.delete()

    messages.success(request, 'Strain deleted successfully.')

    return redirect('strain_list')


@login_required
def strain_edit(request, pk):
    strain = get_object_or_404(Strain, pk=pk)

    if request.method == 'POST':
        form = AddStrainForm(request.POST, instance=strain)

        if form.is_valid():
            form.save()

            messages.success(request, 'Changes saved successfully.')

            return redirect(strain_list)

    else:
        form = AddStrainForm(instance=strain)

    return render(request, 'strain/strain_edit.html', {
        'form': form
    })

userprofile/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

from .models import Userprofile

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            Userprofile.objects.create(user=user)

            return redirect('/log-in/')
    else:
        form = UserCreationForm()

    return render(request, 'userprofile/signup.html', {
        'form': form,
        })

concentrates/templates/concentrates/concentrate_detail.html
{% extends 'core/base.html' %}

{% block content %}

    <h1 class="text-4xl text-center mb-4">{{ concentrate.name }}</h1>

    <div class="grid grid-cols-1 place-items-center">
        <div></div>
        <div class="col-md-4">
            <img src="{{ concentrate.image.url }}" style="max-height: 360px; max-width: 360px;">
        </div>
        <div></div>
    </div>

    <div class="grid grid-cols-1 gap-4 mx-4 mt-6 place-items-center font-bold">
        <p>Description</p>
    </div>

    <div class="grid grid-cols-1 mx-4 place-items-center">
        <div class="bg-gray-100 border-2 rounded-lg border-green-400 max-w-xl max-h-32
            overflow-auto whitespace-pre-line py-1 px-3">{{ concentrate.description }}
        </div>
    </div>
{% endblock %}}

concentrates/templates/concentrates/concentrate_list.html
{% extends 'core/base.html' %}

{% block title %}Concentrates{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-center mb-4 text-3xl font-bold">Concentrates</h1>


        {% if concentrates %}
            {% for concentrate in concentrates %}
                <div onclick="location.href='{% url 'concentrates:concentrate_detail' concentrate.id %}';" class="relative grid grid-cols-3 grid-rows-5 mx-auto max-w-xs -m-4 py-6">
                    <div class="grid grid-cols-3 row-start-2 row-span-3 col-span-3 rounded-xl shadow-2xl bg-opacity-50 bg-indigo-300">
                        <div style="overflow: visible;" class="absolute top-18 left-16" >
                            <img src="{{ concentrate.image.url }}" style="width: 80%; height: auto;">
                        </div>

                        <div  class="text-[17px] px-2 font-bold col-span-2 tracking-tight">
                        <a>{{ concentrate.name }}</a>
                        </div>

                        <div class="col-span-2 px-2 mt-2 mb-2">
                            <span class="font-semibold underline mx-1"></span>
                            <ul>
                            {% for effect in strain.effect %}
                                 <li class="text-sm">&nbsp {{ effect.title }}</li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="mt= 6 px-2">No strains to display.</div>
        {% endif %}
    </div>
{% endblock %}

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}About{% endblock %}

{% block content %}
<div class="grid grid-cols-1 mx-4 place-items-center">
    <div class="bg-gray-100 border-2 rounded-lg border-green-400 max-w-2xl px-4 m-8 whitespace-pre-line relative">
        <h1 class="text-center font-bold text-2xl">About Us</h1>
        <h2 class="font-semibold -mb-5">Who we are:</h2>
        <p class="text-sm">We are an organic cannabis micro-farm striving for perfection in the indoor organic cannabis space.</p>
        <h2 class="font-semibold -mb-5">What is organic cannabis?</h2>
        <p class="text-sm">Organic cannabis is cannabis that is grown without the use of synthetic pesticides, fertilizers, or other artificial chemicals. Instead, it is grown using natural methods and materials, such as compost and natural pest control methods, to produce a product that is pure and free of harmful chemicals. Because organic cannabis is grown without the use of synthetic chemicals, it is often considered to be of higher quality and is sought after by many consumers for its purity and potential health benefits.</p>
        <h2 class="font-semibold -mb-5">Why should you care about organic cannabis?</h2>
        <p class="text-sm">Organically grown cannabis is becoming increasingly popular among consumers who are looking for a healthier and more sustainable option. While cannabis grown with synthetic fertilizers may be more convenient and cost-effective for growers, it can have negative effects on both the quality and safety of the final product.

One of the main benefits of consuming organically grown cannabis is the improved quality of the plant. Organic growing methods rely on natural fertilizers and pesticides, which can enhance the flavor and aroma of the cannabis. In contrast, cannabis grown with synthetic fertilizers can often have a harsh, chemical taste.

Probably the most important benefit of organic cannabis is that it is safer for consumers. Synthetic fertilizers and pesticides used in non-organic growing methods can contain harmful chemicals that can potentially be ingested by the consumer. In contrast, organic growing methods use natural fertilizers and pesticides that are safer for both the plant and the consumer.

In addition to the improved taste and safety of organic cannabis, there are also several other benefits of consuming this type of product. For example, organic growing methods often produce cannabis with a higher concentration of beneficial compounds like terpenes and cannabinoids. These compounds are responsible for the therapeutic effects of cannabis, and a higher concentration can provide a more potent and effective experience for the consumer.

Another benefit of organic cannabis is its sustainability. Synthetic fertilizers and pesticides can have negative effects on the environment, including soil and water contamination. In contrast, organic growing methods are more sustainable and can help protect the environment. Additionally, supporting organic cannabis growers can also have a positive impact on the industry as a whole. By choosing to purchase organic cannabis products, consumers can help support growers who are using sustainable and environmentally-friendly methods. This, in turn, can help encourage more growers to switch to organic methods and promote the overall growth of the organic cannabis industry.

Overall, consuming organically grown cannabis has numerous benefits, including improved quality, safety, and sustainability. By choosing to purchase organic cannabis products, consumers can support sustainable growing practices, experience improved therapeutic effects, and enjoy a better overall experience. While it may be more expensive and time-consuming for growers to produce, it is worth it for the improved product and peace of mind for consumers.

        </p>
    </div>
</div>
{% endblock %}

core/templates/core/base.html
<!doctype html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>

        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">

        <title>{% block title %}{% endblock %}</title>

    </head>
    <body>
        <nav class="py-3 px-6 flex justify-between bg-green-500">
            <a href="{% url 'index' %}" class="py-4 px-4 bg-green-600 hover:bg-green-700 rounded-xl text-white">Home</a>
            <a href="/" class="py-3 text-3xl text-white">Best Buds</a>
            <a href="{% url 'about' %}" class="py-4 px-4 bg-green-600 hover:bg-green-700 rounded-xl text-white">About</a>
        </nav>

        {% if messages %}
            <div class="py-6 px-6">
                {% for message in messages %}
                    <div class="py-4 px-4 bg-green-300 rounded-xl">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% block content %}
        {% endblock %}

        <footer class="py-8 mt-8 bg-gray-200 text-center">
            <p class="text-xs text-gray-700" >Copyright (c) 2022 - Best Buds</p>
        </footer>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Best Buds{% endblock %}

{% block content %}
    <div class="px-4 py-4">
        <h1 class="text-center font-bold text-2xl mb-2">Products</h1>
        <div class="grid grid-cols-2 justify-self-center">
            <div onclick="location.href='{% url 'strains:strain_list' %}';" class="flex flex-col rounded-lg bg-gray-100 border-2 shadow-xl h-32 w-32 justify-self-end m-2">
                <img src="{% static 'img/flower.png' %}" class="h-1/2 w-1/2 mt-6 place-self-center">
                <div class="mt-auto mb-2 mx-auto font-semibold">Flower</div>
            </div>
            <div onclick="location.href='{% url 'concentrates:concentrate_list' %}';"class="flex flex-col rounded-lg bg-gray-100 border-2 shadow-xl h-32 w-32 justify-self-start m-2 relative">
                <img src="{% static 'img/concentrates.png' %}" class="h-1/2 w-1/2 mt-6 place-self-center">
                <div class="mt-auto mb-2 mx-auto font-semibold">Concentrates</div>
            </div>
            <div onclick="location.href='{% url 'trim' %}';" class="flex flex-col rounded-lg bg-gray-100 border-2 shadow-xl h-32 w-32 justify-self-end m-2">
                <img src="{% static 'img/trim.png' %}" class="h-1/2 w-1/2 mt-6 place-self-center">
                <div class="mt-auto mb-2 mx-auto font-semibold">Trim</div>
            </div>
            <div class="flex flex-col rounded-lg bg-gray-100 border-2 shadow-xl h-32 w-32 justify-self-start m-2 relative">
                <div style="overflow: visible" class="absolute top-6 right-3">
                    <img src="{% static 'img/coming_soon.png' %}" style="width: 100px">
                </div>
                <img src="{% static 'img/edibles.png' %}" class="h-1/2 w-1/2 mt-6 place-self-center">
                <div class="mt-auto mb-2 mx-auto font-semibold">Edibles</div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/trim.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

    <h1 class="text-4xl text-center m-4">Trim and<br>Popcorn Bud</h1>

    <div class="grid grid-cols-1 place-items-center">
        <div></div>
        <div class="col-md-4">
            <img src="{% static 'img/trimpic.png' %}" style="max-height: 360px">
        </div>
        <div></div>
    </div>

    <div class="grid grid-cols-1 gap-4 mx-4 mt-4 place-items-center font-bold">
        <p>Description</p>
    </div>

    <div class="grid grid-cols-1 mx-4 place-items-center">
        <div class="bg-gray-100 border-2 rounded-lg border-green-400 max-w-xl max-h-32
        overflow-auto whitespace-pre-line py-1 px-3">Cannabis trim is the sugar leaves that are collected after a harvest is trimmed. Our trimming process involves removing the fan leaves prior to trimming, so the trim we offer consists only of the most flavorful and potent parts of the plant.

            Popcorn bud refers to small flowers that are about the size of popcorn. Our trim product includes popcorn buds that weren't quite large enough to make it into the flower jars. This makes our trim product a great value!

            There are many ways to use cannabis trim, from making concentrates like rosin or hash, to adding it to joints or bowls for an extra kick of flavor. You can even use it to make edibles by decarboxylating the trim and mixing it into your favorite cannabis recipes.

            Whether you're a seasoned cannabis consumer or just getting started, cannabis trim is a great option to have on hand. It's versatile, cost-effective, and can add a whole new dimension to your consumption experience.

            Give it a try and see for yourself!
        </div>
    </div>
{% endblock %}}

strains/templates/strains/add_strain.html
{% extends 'core/base.html' %}


{% block title %}Add Strain{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Add a strain</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p}}

            <button class="py-3 px-6 bg-green-500 text-white rounded-xl">Submit</button>
        </form>

    </div>

{% endblock %}

strains/templates/strains/strain_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="grid grid-cols-1 place-items-center">
        <div class="text-center m-4">
            <div class="text-4xl">
                {{ strain.name }}
            </div>
        </div>
        <div class="col-md-4">
            <img src="{{ strain.image.url }}" style="max-height: 360px; margin-bottom: 1rem">
        </div>
        <div></div>
    </div>


    <div class="flex justify-center items-center gap-4 mx-4 place-items-center font-bold">
        <p class="w-28 text-center">Type</p>
        <p class="w-28 text-center">THC</p>
        <p class="w-28 text-center">Breeder</p>
    </div>

    <div class="flex justify-center items-center gap-4 mx-4 place-items-center">
        <div class="bg-gray-100 border-2 rounded-lg border-green-400 h-16 w-28 max-w-xs">
            <p class="flex justify-center items-center text-center text-sm h-16">{{ strain.get_type_display }}</p>
        </div>
        <div class="bg-gray-100 border-2 rounded-lg border-green-400 h-16 w-28 max-w-xs">
            <p class="flex justify-center items-center text-center text-sm h-16">{{ strain.thc }}%</p>
        </div>
        <div class="bg-gray-100 border-2 rounded-lg border-green-400 h-16 w-28 max-w-xs">
            <p class="flex justify-center items-center text-center text-sm h-16">{{ strain.breeder}}</p>
        </div>
    </div>


    <div class="flex justify-center items-center gap-4 mx-4 place-items-center font-bold">
        <p class="w-28 text-center">Effects</p>
        <p class="w-28 text-center">Aroma/Flavor</p>
        <p class="w-28 text-center">Lineage</p>
    </div>

    <div class="flex justify-center items-center gap-4 mx-4 place-items-center">
        <div class="bg-gray-100 border-2 rounded-lg border-green-400 w-28 max-w-xs overflow-auto">
            <p class="flex justify-center items-center text-center text-sm h-16">{{ strain.get_effect_display}}</p>
        </div>
        <div class="bg-gray-100 border-2 rounded-lg border-green-400 w-28 max-w-xs overflow-auto">
            <p class="flex justify-center items-center text-center text-sm h-16">{{ strain.get_aroma_display }}</p>
        </div>
        <div class="bg-gray-100 border-2 rounded-lg border-green-400 w-28 max-w-xs overflow-auto">
            <p class="flex justify-center items-center text-center text-sm h-16">{{ strain.lineage }}</p>
        </div>
    </div>

    <div class="grid grid-cols-1 gap-4 mx-4 mt-4 place-items-center font-bold">
        <p>Description</p>
    </div>

    <div class="grid grid-cols-1 mx-4 place-items-center">
        <div class="bg-gray-100 border-2 rounded-lg border-green-400 max-w-xl max-h-32
        overflow-auto whitespace-pre-line py-1 px-3">{{ strain.description }}
        </div>
    </div>

    <div class="grid grid-cols-1 mx-4 mt-4 place-items-center font-bold">
        <p>Grow Information</p>
    </div>

    <div class="grid grid-cols-1 mx-4 place-items-center">
        <div class="bg-gray-100 border-2 rounded-lg border-green-400 max-w-xl max-h-32
        overflow-auto whitespace-pre-line py-1 px-3">{{ strain.grow_info }}"
        </div>
    </div>
{% endblock %}}

strains/templates/strains/strain_edit.html
{% extends 'core/base.html' %}

{% block title %}Edit Strain{% endblock %}

{% block content %}

    <h1>{{ strain.name }}</h1>
    <div class="py-6 px-6">
        <h1 class="text-xl">Edit Strain</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p}}

            <button class="py-3 px-6 bg-green-500 text-white rounded-xl">Submit</button>
        </form>

    </div>

{% endblock %}

strains/templates/strains/strain_list.html
{% extends 'core/base.html' %}

{% block title %}Strains{% endblock %}

{% block content %}
    {% if not request.GET.stock %}
        <script>
            window.location.href = "{% url 'strains:strain_list' %}?stock=in_stock";
        </script>
    {% endif %}
    <div class="py-6 px-6">
        <h1 class="text-center mb-4 text-3xl font-bold">Flower</h1>
        <form method="get" action="{% url 'strains:strain_list' %}">
            <div class="mb-8 max-w-xs text-center mx-auto">
                <div class="relative">
                    <select name="stock" id="stock" class="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline">
                        <option value="in_stock"{% if request.GET.stock == "in_stock" %} selected{% endif %}>In Stock</option>
                        <option value="out_of_stock"{% if request.GET.stock == "out_of_stock" %} selected{% endif %}>Out of Stock</option>
                        <option value="coming_soon"{% if request.GET.stock == "coming_soon" %} selected{% endif %}>Coming Soon</option>
                        <option value="gone_forever"{% if request.GET.stock == "gone_forever" %} selected{% endif %}>Gone Forever</option>
                        <option value="all"{% if request.GET.stock == "all" %} selected{% endif %}>All Strains</option>
                    </select>
                    <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                        <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l6.293-6.293a1 1 0 011.414 1.414l-7 7z"/></svg>
                    </div>
                </div>
            </div>
        </form>

        {% if strains %}
            {% for strain in strains %}
                {% if request.GET.stock == "all" or strain.stock == request.GET.stock %}
                    <div onclick="location.href='{% url 'strains:strain_detail' strain.id %}';" class="relative grid grid-cols-3 grid-rows-5 mx-auto max-w-xs -m-4">
                        <div class="grid grid-cols-3 row-start-2 row-span-3 col-span-3 rounded-xl shadow-2xl bg-opacity-50
                            {% if strain.get_type_display == 'Sativa' %}bg-yellow-300
                            {% elif strain.get_type_display == 'Sativa Hybrid' %}bg-yellow-300
                            {% elif strain.get_type_display == 'Hybrid' %}bg-emerald-300
                            {% elif strain.get_type_display == 'Indica Hybrid' %}bg-indigo-300
                            {% else %}bg-indigo-300
                            {% endif %}">
                            <div style="overflow: visible" class="absolute top-5 -right-3 row-span-5 row-start-1">
                                <img src="{{ strain.image.url }}" style="height: 230px">
                            </div>
                            <div class="col-span-2 px-2 py-2">
                                <a class="px-2 rounded-lg font-bold
                                    {% if strain.get_type_display == 'Sativa' %}bg-yellow-300 text-yellow-900
                                    {% elif strain.get_type_display == 'Sativa Hybrid' %}bg-yellow-300 text-yellow-900
                                    {% elif strain.get_type_display == 'Hybrid' %}bg-emerald-300 text-emerald-900
                                    {% elif strain.get_type_display == 'Indica Hybrid' %}bg-indigo-300 text-indigo-900
                                    {% else %}bg-indigo-300 text-indigo-900
                                    {% endif %}">{{ strain.get_type_display}}
                                </a>
                            </div>
                            <div class="text-[17px] px-2 font-bold col-span-2 tracking-tight">
                            <a>{{ strain.name }}</a>
                            </div>
                            <div class="col-span-2 px-2 mt-2 mb-2">
                                <span class="font-semibold underline mx-1">Effects:</span>
                                <ul>
                                {% for effect in strain.effect %}
                                     <li class="text-sm">&nbsp {{ effect.title }}</li>
                                {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <div class="mt-6 px-2 text-center">No strains to display.</div>
        {% endif %}
    </div>

    <script>
        const stockSelect = document.getElementById("stock");
        stockSelect.addEventListener("change", function() {
            const selectedValue = stockSelect.options[stockSelect.selectedIndex].value;
            window.location.href = "{% url 'strains:strain_list' %}?stock=" + selectedValue;
        });
    </script>

{% endblock %}

userprofile/templates/userprofile/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <h1 class="text-xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-3 px-6 bg-green-500 text-white rounded-xl">Submit</button>
    </form>

{% endblock %}

userprofile/templates/userprofile/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <h1 class="text-xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-3 px-6 bg-green-500 text-white rounded-xl">Submit</button>
    </form>

{% endblock %}